name: UBC Editor Configuration
type: module
description: This module defines default configuration for Drupal's WYSIWYG, cKeditor.
package: UBC Web Services
dependencies:
  - drupal:ckeditor
  - ubc_ckeditor_widgets:ubc_ckeditor_widgets
  - ubc_image_styles:ubc_image_styles
core: '8.x'
