name: UBC General Shared Configuration
type: module
description: This module defines shared configuration items (ie. display modes, taxonomies, etc).
package: UBC Web Services
dependencies:
  - drupal:node
  - drupal:structure_sync
  - drupal:taxonomy
core: '8.x'
