# Schema for the configuration files of the galactus theme.
ubc_layout_config.ubc_general_settings:
  type: theme_settings
  label: 'ubc layout general settings'

ubc_layout_config.ubc_homepage_settings:
  type: theme_settings
  label: 'ubc layout homepage settings'

ubc_layout_config.ubc_landing_page_settings:
  type: theme_settings
  label: 'ubc layout landing page settings'

ubc_layout_config.ubc_page_settings:
  type: theme_settings
  label: 'ubc layout page settings'

ubc_layout_config.ubc_announcement_settings:
  type: theme_settings
  label: 'ubc layout announcement settings'
